language: go
go:
  - 1.11.2

script:
  - go test ./...

services:
  - mysql
  - postgresql
  - rabbitmq
  - docker

env:
- CONSUL_VERSION=1.4.2

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_test;'
  - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul.zip -d $HOME/bin
  - docker run -it -d -p8332:8332 -p8334:8334 -eRPCUSER=admin -eRPCPASSWORD=123456 andboson/bitcoin-test:dev
  - docker ps -a

before_script:
  - psql -c 'CREATE DATABASE db_test;' -U postgres
