language: go
go:
  - 1.11.2

script:
  - go test ./...

services:
  - mysql
  - postgresql
  - rabbitmq
  - docker

env:
- CONSUL_VERSION=1.4.2

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_test;'
  - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul.zip -d $HOME/bin
  - cd btc-rpc/testnet && docker build -t dockertest .
  - docker run -d -p 127.0.0.1:8332:8332 -p 127.0.0.1:8334:8334 dockertest
  - docker ps -a

before_script:
  - psql -c 'CREATE DATABASE db_test;' -U postgres
